[package]
name = "milvus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
milvus-sdk-rust = "0.1.0"
tokio = "1.34.0"
